# Generated by Django 3.1.3 on 2023-02-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(default='')),
                ('fundacion', models.TextField(default='')),
                ('continente', models.TextField(default='')),
                ('trofeos', models.IntegerField(default=0)),
                ('presidente', models.TextField(default='')),
                ('pais', models.TextField(default='')),
                ('liga', models.TextField(default='')),
                ('trofeosinte', models.IntegerField(default=0)),
                ('trofeosloca', models.IntegerField(default=0)),
                ('numerojuga', models.IntegerField(default=0)),
            ],
        ),
    ]
