# Generated by Django 3.1.3 on 2023-02-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='fundacion',
            field=models.IntegerField(default=''),
        ),
    ]
