# Generated by Django 3.1.3 on 2023-03-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_auto_20230224_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='fundacion',
            field=models.IntegerField(default=0),
        ),
    ]
